### ISSUE TITLE
Sliders don't work on polygon with holes

### ISSUE THREAD

**Issue by hasanbinboga** [dwilhelm89/Leaflet.StyleEditor#84] opened 2019-09-25 12:14 UTC
Hi, 
The plugin is quite simple and straightforward to use. I could easily identify it. However, in my tests, I saw that the sliders did not work on polygons with holes. 
Below is an example geojson;

{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature","properties": {}, "geometry": { "type": "Polygon",
        "coordinates": [
          [
            [
              11.620617,
              48.236794
            ]
            [
              11.620617,
              48.237251
            ]
            [
              11.725159,
              48.237251
            ]
            [
              11.725159,
              48.236794
            ]
            [
              11.620617,
              48.236794
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              11.575298,
              48.207401
            ]
            [
              11.575298,
              48.247197
            ]
            [
              11.712112,
              48.247197
            ]
            [
              11.712112,
              48.207401
            ]
            [
              11.575298,
              48.207401
            ]
          ]
        ]
      }
    }
  ]
}

Best regards.

**Comment by fupduck** [comment] 2019-10-15 18:36
Hi @hasanbinboga !

Thanks for the report.
I was not able to reproduce the error. In the image below everything worked fine for me.

![hole](https://user-images.githubusercontent.com/140332/66859337-5fe75700-ef8b-11e9-9790-11986a7c296f.png)

Are you still able to reproduce the error?

**Comment by fupduck** [comment] 2019-10-29 22:40
@hasanbinboga 
closing because I don't have enough information, feel free to contact me again if you have more :)

**Closed by fupduck** 2019-10-29 22:40 UTC
